"""initial schema

Revision ID: d185c6f2ed6d
Revises: 
Create Date: 2026-08-31 01:30:21.261526
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acknowledgement_configs',
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('reaction_type', sa.String(length=32), nullable=False),
    sa.Column('reaction_value', sa.String(length=64), nullable=True),
    sa.Column('target_mode', sa.String(length=32), nullable=False),
    sa.Column('dispatch_policy', sa.String(length=48), nullable=False),
    sa.Column('retry_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acknowledgement_configs')),
    sa.UniqueConstraint('status', name=op.f('uq_acknowledgement_configs_status'))
    )
    op.create_table('admins',
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('from_env', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
    sa.UniqueConstraint('telegram_user_id', name=op.f('uq_admins_telegram_user_id'))
    )
    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_created_at_id', 'audit_logs', ['created_at', 'id'], unique=False)
    op.create_index(op.f('ix_audit_logs_event'), 'audit_logs', ['event'], unique=False)
    op.create_index(op.f('ix_audit_logs_order_id'), 'audit_logs', ['order_id'], unique=False)
    op.create_table('daily_counters',
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('scope_key', sa.String(length=64), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_counters')),
    sa.UniqueConstraint('business_date', 'scope_key', name=op.f('uq_daily_counters_business_date_scope_key'))
    )
    op.create_index(op.f('ix_daily_counters_business_date'), 'daily_counters', ['business_date'], unique=False)
    op.create_table('notification_throttle',
    sa.Column('notification_key', sa.String(length=256), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_throttle')),
    sa.UniqueConstraint('notification_key', name=op.f('uq_notification_throttle_notification_key'))
    )
    op.create_table('operators',
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('all_work_groups', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operators')),
    sa.UniqueConstraint('telegram_user_id', name=op.f('uq_operators_telegram_user_id'))
    )
    op.create_table('processed_updates',
    sa.Column('update_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processed_updates')),
    sa.UniqueConstraint('update_key', name=op.f('uq_processed_updates_update_key'))
    )
    op.create_index(op.f('ix_processed_updates_created_at'), 'processed_updates', ['created_at'], unique=False)
    op.create_table('result_destinations',
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_result_destinations')),
    sa.UniqueConstraint('status', 'chat_id', name=op.f('uq_result_destinations_status_chat_id'))
    )
    op.create_index(op.f('ix_result_destinations_status'), 'result_destinations', ['status'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
    sa.UniqueConstraint('key', name=op.f('uq_settings_key'))
    )
    op.create_table('source_channels',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_channels')),
    sa.UniqueConstraint('chat_id', name=op.f('uq_source_channels_chat_id'))
    )
    op.create_table('status_rules',
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status_rules')),
    sa.UniqueConstraint('status', name=op.f('uq_status_rules_status'))
    )
    op.create_table('work_groups',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_groups')),
    sa.UniqueConstraint('chat_id', name=op.f('uq_work_groups_chat_id'))
    )
    op.create_table('operator_work_groups',
    sa.Column('operator_id', sa.BigInteger(), nullable=False),
    sa.Column('work_group_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('fk_operator_work_groups_operator_id_operators'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_group_id'], ['work_groups.id'], name=op.f('fk_operator_work_groups_work_group_id_work_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operator_work_groups')),
    sa.UniqueConstraint('operator_id', 'work_group_id', name=op.f('uq_operator_work_groups_operator_id_work_group_id'))
    )
    op.create_index(op.f('ix_operator_work_groups_operator_id'), 'operator_work_groups', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_work_groups_work_group_id'), 'operator_work_groups', ['work_group_id'], unique=False)
    op.create_table('orders',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('daily_number', sa.Integer(), nullable=False),
    sa.Column('counter_scope_key', sa.String(length=64), nullable=False),
    sa.Column('display_number', sa.String(length=64), nullable=False),
    sa.Column('source_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('source_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('source_message_id', sa.BigInteger(), nullable=False),
    sa.Column('source_media_group_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('completion_trigger_type', sa.String(length=32), nullable=True),
    sa.Column('completion_trigger_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('completion_trigger_message_id', sa.BigInteger(), nullable=True),
    sa.Column('success_reason', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('result_dispatch_status', sa.String(length=32), nullable=False),
    sa.Column('acknowledgement_status', sa.String(length=32), nullable=False),
    sa.Column('acknowledgement_reaction', sa.String(length=32), nullable=True),
    sa.Column('acknowledgement_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('acknowledgement_message_id', sa.BigInteger(), nullable=True),
    sa.Column('acknowledgement_applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledgement_attempts', sa.Integer(), nullable=False),
    sa.Column('acknowledgement_error', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_channel_id'], ['source_channels.id'], name=op.f('fk_orders_source_channel_id_source_channels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('business_date', 'counter_scope_key', 'daily_number', name=op.f('uq_orders_business_date_counter_scope_key_daily_number')),
    sa.UniqueConstraint('source_chat_id', 'source_message_id', name=op.f('uq_orders_source_chat_id_source_message_id')),
    sa.UniqueConstraint('uuid', name=op.f('uq_orders_uuid'))
    )
    op.create_index(op.f('ix_orders_business_date'), 'orders', ['business_date'], unique=False)
    op.create_index(op.f('ix_orders_source_channel_id'), 'orders', ['source_channel_id'], unique=False)
    op.create_index(op.f('ix_orders_source_media_group_id'), 'orders', ['source_media_group_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index('ix_orders_status_business_date', 'orders', ['status', 'business_date'], unique=False)
    op.create_index('uq_orders_source_media_group', 'orders', ['source_chat_id', 'source_media_group_id'], unique=True, postgresql_where=sa.text('source_media_group_id IS NOT NULL'))
    op.create_table('routes',
    sa.Column('source_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('work_group_id', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_channel_id'], ['source_channels.id'], name=op.f('fk_routes_source_channel_id_source_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_group_id'], ['work_groups.id'], name=op.f('fk_routes_work_group_id_work_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes')),
    sa.UniqueConstraint('source_channel_id', 'work_group_id', name=op.f('uq_routes_source_channel_id_work_group_id'))
    )
    op.create_index(op.f('ix_routes_source_channel_id'), 'routes', ['source_channel_id'], unique=False)
    op.create_index(op.f('ix_routes_work_group_id'), 'routes', ['work_group_id'], unique=False)
    op.create_table('rule_reactions',
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('emoji', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['status_rules.id'], name=op.f('fk_rule_reactions_rule_id_status_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_reactions')),
    sa.UniqueConstraint('rule_id', 'emoji', name=op.f('uq_rule_reactions_rule_id_emoji'))
    )
    op.create_index(op.f('ix_rule_reactions_rule_id'), 'rule_reactions', ['rule_id'], unique=False)
    op.create_table('rule_signals',
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('signal_key', sa.String(length=48), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['status_rules.id'], name=op.f('fk_rule_signals_rule_id_status_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_signals')),
    sa.UniqueConstraint('rule_id', 'signal_key', name=op.f('uq_rule_signals_rule_id_signal_key'))
    )
    op.create_index(op.f('ix_rule_signals_rule_id'), 'rule_signals', ['rule_id'], unique=False)
    op.create_table('rule_text_patterns',
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('match_mode', sa.String(length=16), nullable=False),
    sa.Column('case_sensitive', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['status_rules.id'], name=op.f('fk_rule_text_patterns_rule_id_status_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_text_patterns'))
    )
    op.create_index(op.f('ix_rule_text_patterns_rule_id'), 'rule_text_patterns', ['rule_id'], unique=False)
    op.create_table('acknowledgement_events',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('order_status', sa.String(length=32), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('reaction', sa.String(length=64), nullable=True),
    sa.Column('target_mode', sa.String(length=32), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_acknowledgement_events_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acknowledgement_events'))
    )
    op.create_index(op.f('ix_acknowledgement_events_order_id'), 'acknowledgement_events', ['order_id'], unique=False)
    op.create_table('order_deliveries',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('work_group_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_deliveries_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_group_id'], ['work_groups.id'], name=op.f('fk_order_deliveries_work_group_id_work_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_deliveries')),
    sa.UniqueConstraint('order_id', 'work_group_id', name=op.f('uq_order_deliveries_order_id_work_group_id'))
    )
    op.create_index(op.f('ix_order_deliveries_chat_id'), 'order_deliveries', ['chat_id'], unique=False)
    op.create_index(op.f('ix_order_deliveries_order_id'), 'order_deliveries', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_deliveries_work_group_id'), 'order_deliveries', ['work_group_id'], unique=False)
    op.create_table('order_signals',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_status', sa.String(length=32), nullable=False),
    sa.Column('signal_key', sa.String(length=48), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('trigger_type', sa.String(length=32), nullable=True),
    sa.Column('trigger_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('trigger_message_id', sa.BigInteger(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_signals_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_signals')),
    sa.UniqueConstraint('order_id', 'rule_status', 'signal_key', name=op.f('uq_order_signals_order_id_rule_status_signal_key'))
    )
    op.create_index(op.f('ix_order_signals_order_id'), 'order_signals', ['order_id'], unique=False)
    op.create_table('order_source_messages',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('media_group_id', sa.String(length=64), nullable=True),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('file_id', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('caption_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_spoiler', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_source_messages_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_source_messages')),
    sa.UniqueConstraint('chat_id', 'message_id', name=op.f('uq_order_source_messages_chat_id_message_id'))
    )
    op.create_index(op.f('ix_order_source_messages_order_id'), 'order_source_messages', ['order_id'], unique=False)
    op.create_table('result_dispatches',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('destination_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('order_status', sa.String(length=32), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('sent_message_id', sa.BigInteger(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['result_destinations.id'], name=op.f('fk_result_dispatches_destination_id_result_destinations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_result_dispatches_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_result_dispatches')),
    sa.UniqueConstraint('order_id', 'destination_id', name=op.f('uq_result_dispatches_order_id_destination_id'))
    )
    op.create_index(op.f('ix_result_dispatches_destination_id'), 'result_dispatches', ['destination_id'], unique=False)
    op.create_index(op.f('ix_result_dispatches_order_id'), 'result_dispatches', ['order_id'], unique=False)
    op.create_index(op.f('ix_result_dispatches_status'), 'result_dispatches', ['status'], unique=False)
    op.create_table('status_events',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('trigger_type', sa.String(length=32), nullable=True),
    sa.Column('trigger_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('trigger_message_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_status_events_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status_events'))
    )
    op.create_index(op.f('ix_status_events_order_id'), 'status_events', ['order_id'], unique=False)
    op.create_table('order_delivery_messages',
    sa.Column('delivery_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['order_deliveries.id'], name=op.f('fk_order_delivery_messages_delivery_id_order_deliveries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_delivery_messages_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_delivery_messages')),
    sa.UniqueConstraint('chat_id', 'message_id', name=op.f('uq_order_delivery_messages_chat_id_message_id'))
    )
    op.create_index(op.f('ix_order_delivery_messages_delivery_id'), 'order_delivery_messages', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_order_delivery_messages_order_id'), 'order_delivery_messages', ['order_id'], unique=False)
    op.create_index('ix_order_delivery_messages_order_primary', 'order_delivery_messages', ['order_id', 'is_primary'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_delivery_messages_order_primary', table_name='order_delivery_messages')
    op.drop_index(op.f('ix_order_delivery_messages_order_id'), table_name='order_delivery_messages')
    op.drop_index(op.f('ix_order_delivery_messages_delivery_id'), table_name='order_delivery_messages')
    op.drop_table('order_delivery_messages')
    op.drop_index(op.f('ix_status_events_order_id'), table_name='status_events')
    op.drop_table('status_events')
    op.drop_index(op.f('ix_result_dispatches_status'), table_name='result_dispatches')
    op.drop_index(op.f('ix_result_dispatches_order_id'), table_name='result_dispatches')
    op.drop_index(op.f('ix_result_dispatches_destination_id'), table_name='result_dispatches')
    op.drop_table('result_dispatches')
    op.drop_index(op.f('ix_order_source_messages_order_id'), table_name='order_source_messages')
    op.drop_table('order_source_messages')
    op.drop_index(op.f('ix_order_signals_order_id'), table_name='order_signals')
    op.drop_table('order_signals')
    op.drop_index(op.f('ix_order_deliveries_work_group_id'), table_name='order_deliveries')
    op.drop_index(op.f('ix_order_deliveries_order_id'), table_name='order_deliveries')
    op.drop_index(op.f('ix_order_deliveries_chat_id'), table_name='order_deliveries')
    op.drop_table('order_deliveries')
    op.drop_index(op.f('ix_acknowledgement_events_order_id'), table_name='acknowledgement_events')
    op.drop_table('acknowledgement_events')
    op.drop_index(op.f('ix_rule_text_patterns_rule_id'), table_name='rule_text_patterns')
    op.drop_table('rule_text_patterns')
    op.drop_index(op.f('ix_rule_signals_rule_id'), table_name='rule_signals')
    op.drop_table('rule_signals')
    op.drop_index(op.f('ix_rule_reactions_rule_id'), table_name='rule_reactions')
    op.drop_table('rule_reactions')
    op.drop_index(op.f('ix_routes_work_group_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_source_channel_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index('uq_orders_source_media_group', table_name='orders', postgresql_where=sa.text('source_media_group_id IS NOT NULL'))
    op.drop_index('ix_orders_status_business_date', table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_source_media_group_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_source_channel_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_business_date'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_operator_work_groups_work_group_id'), table_name='operator_work_groups')
    op.drop_index(op.f('ix_operator_work_groups_operator_id'), table_name='operator_work_groups')
    op.drop_table('operator_work_groups')
    op.drop_table('work_groups')
    op.drop_table('status_rules')
    op.drop_table('source_channels')
    op.drop_table('settings')
    op.drop_index(op.f('ix_result_destinations_status'), table_name='result_destinations')
    op.drop_table('result_destinations')
    op.drop_index(op.f('ix_processed_updates_created_at'), table_name='processed_updates')
    op.drop_table('processed_updates')
    op.drop_table('operators')
    op.drop_table('notification_throttle')
    op.drop_index(op.f('ix_daily_counters_business_date'), table_name='daily_counters')
    op.drop_table('daily_counters')
    op.drop_index(op.f('ix_audit_logs_order_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at_id', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('admins')
    op.drop_table('acknowledgement_configs')
    # ### end Alembic commands ###
