"""order number, source reactions, attachments, woocommerce

Revision ID: ec4e3fffaefa
Revises: 0001_initial
Create Date: 2026-09-01 00:37:20.832080
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002_extensions'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_reactions',
    sa.Column('emoji', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progress_reactions')),
    sa.UniqueConstraint('emoji', name=op.f('uq_progress_reactions_emoji'))
    )
    op.create_table('rejected_messages',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('author_user_id', sa.BigInteger(), nullable=True),
    sa.Column('author_name', sa.String(length=256), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rejected_messages')),
    sa.UniqueConstraint('chat_id', 'message_id', name=op.f('uq_rejected_messages_chat_id_message_id'))
    )
    op.create_index(op.f('ix_rejected_messages_created_at'), 'rejected_messages', ['created_at'], unique=False)
    op.create_table('result_configs',
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('append_text_enabled', sa.Boolean(), nullable=False),
    sa.Column('append_text', sa.Text(), nullable=True),
    sa.Column('woo_enabled', sa.Boolean(), nullable=False),
    sa.Column('woo_status', sa.String(length=64), nullable=True),
    sa.Column('woo_note_enabled', sa.Boolean(), nullable=False),
    sa.Column('woo_note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_result_configs')),
    sa.UniqueConstraint('status', name=op.f('uq_result_configs_status'))
    )
    op.create_table('source_reaction_configs',
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('reaction_value', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_reaction_configs')),
    sa.UniqueConstraint('stage', name=op.f('uq_source_reaction_configs_stage'))
    )
    op.create_table('order_attachments',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('file_id', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_attachments_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_attachments')),
    sa.UniqueConstraint('chat_id', 'message_id', name=op.f('uq_order_attachments_chat_id_message_id'))
    )
    op.create_index(op.f('ix_order_attachments_order_id'), 'order_attachments', ['order_id'], unique=False)
    op.create_table('woocommerce_calls',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('order_status', sa.String(length=32), nullable=False),
    sa.Column('store_order_number', sa.String(length=32), nullable=False),
    sa.Column('target_status', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_woocommerce_calls_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_woocommerce_calls')),
    sa.UniqueConstraint('order_id', name=op.f('uq_woocommerce_calls_order_id'))
    )
    op.create_index(op.f('ix_woocommerce_calls_order_id'), 'woocommerce_calls', ['order_id'], unique=False)
    op.create_index(op.f('ix_woocommerce_calls_status'), 'woocommerce_calls', ['status'], unique=False)
    op.add_column('orders', sa.Column('source_order_number', sa.String(length=32), nullable=True))
    op.add_column('orders', sa.Column('in_progress_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('in_progress_by_user_id', sa.BigInteger(), nullable=True))
    op.add_column('orders', sa.Column('source_reaction_stage', sa.String(length=32), nullable=True))
    op.add_column('orders', sa.Column('source_reaction_value', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_orders_source_order_number'), 'orders', ['source_order_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_source_order_number'), table_name='orders')
    op.drop_column('orders', 'source_reaction_value')
    op.drop_column('orders', 'source_reaction_stage')
    op.drop_column('orders', 'in_progress_by_user_id')
    op.drop_column('orders', 'in_progress_at')
    op.drop_column('orders', 'source_order_number')
    op.drop_index(op.f('ix_woocommerce_calls_status'), table_name='woocommerce_calls')
    op.drop_index(op.f('ix_woocommerce_calls_order_id'), table_name='woocommerce_calls')
    op.drop_table('woocommerce_calls')
    op.drop_index(op.f('ix_order_attachments_order_id'), table_name='order_attachments')
    op.drop_table('order_attachments')
    op.drop_table('source_reaction_configs')
    op.drop_table('result_configs')
    op.drop_index(op.f('ix_rejected_messages_created_at'), table_name='rejected_messages')
    op.drop_table('rejected_messages')
    op.drop_table('progress_reactions')
    # ### end Alembic commands ###
